# Generated by Django 5.0.2 on 2024-02-16 12:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employee',
            name='hire_date_not_future',
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=datetime.date(2024, 2, 16)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(help_text='Enter valid phone number', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must contain 10 digits', regex='\\d{10}$')]),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(check=models.Q(('hire_date__lte', datetime.date(2024, 2, 16))), name='hire_date_not_future'),
        ),
    ]
